apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cvp4a8rp8-go 
  janus-idp.io/tekton: cvp4a8rp8-go
  backstage.io/kubernetes-id: cvp4a8rp8-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cvp4a8rp8-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml